/* Generated file DO NOT EDIT !!!
 * Generated by /Users/mikkel/easy/settler/scripts/generate-admin-files.js at 18-07-2021 20:07:09
 */
/**
 * Created by mikkel in June 2017.
 */

var versionService = {

  version: function() {
    return "2.0.0"
  }

};

module.exports = versionService;
