module.exports = {
  jurisdiction: 'VIC',
  name: 'VIC Buying',
  overview: {
    complete: 0,
    lists: [
      {
        name: 'Unallocated',
        slugs: [],
      },
      {
        name: 'Engagement',
        slugs: [
          'upload-signed-cos',
          'buyer-nominate',
          'buyer-q',
          'client-auth',
          'read-egl',
          'sign-cdc',
          'sign-caf',
        ],
      },
      {
        name: 'Contract',
        slugs: ['voi', 'go-ahead', 'title-search', 'sign-s27-1', 'unconditional'],
      },
      {
        name: 'Settlement',
        slugs: ['settle-date-time', 'upload-soa', 'confirm-pexa', 'notify-authorities'],
      },
      {
        name: 'Hidden',
        slugs: [
          'approve-caf',
          'cost-disclosure',
          'engagement-letter',
          'assign-con',
          'upload-invoice',
          'process-s27-1',
          'upload-soc',
          'approve-soa',
          'approve-soc',
          'final-inspection',
          'buyer-sro',
          'voi-all',
          'approve-cdc',
          'launch-voi',
          'approve-egl',
        ],
      },
    ],
    name: 'Overview',
    progress: 0,
    status: 'ready',
    total: 0,
  },
  slug: 'vic-buy',
  stages: [
    {
      name: 'Engagement',
      slug: 'engagement',
      steps: [
        {
          config: {},
          customerText: 'Assign conveyancer',
          depends: [],
          doctype: 'na',
          explanation:
            'We will select a conveyancer in your area who has experience with your type of property.',
          external: [],
          internal: true,
          logic: 'before if person.con.present complete me',
          milestone: false,
          name: 'Assign conveyancer',
          notifications: [
            {
              method: 'SMS',
              number: 101,
              recipients: ['CUS'],
              revision: 1,
              text: 'gen.sms.g.101',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 101,
              recipients: ['CUS'],
              revision: 1,
              text: 'gen.app.g.101',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 420,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.sms.v.420',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 420,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.app.v.420',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 550,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.550',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 550,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.550',
              trigger: 'complete',
            },
          ],
          optional: false,
          permissions: {
            approve: ['PM'],
            assign: ['ADM', 'PM'],
            download: ['ADM', 'CON', 'PM', 'CUS'],
            reject: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Practice manager',
          role: 'PM',
          slug: 'assign-con',
          type: 'assign',
        },
        {
          config: {},
          customerText: 'Buyer Contact Authority',
          depends: [],
          description:
            'In this form, you will nominate the people to be on the property title, and who will sign conveyancing documents. We need this to prepare an Engagement Letter, Costs Disclosure and authority to act.',
          doctype: 'bnf',
          explanation:
            'Settle Easy needs to know a little bit more about you. Please complete this form as soon as possible.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Buyer Contact Authority',
          notifications: [
            {
              method: 'EMAIL',
              number: 220,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.e.v.220',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            download: ['ADM', 'CUS'],
            edit: ['ADM', 'CON', 'PM', 'CUS'],
            skip: ['ADM'],
            status: ['ADM', 'CUS'],
            view: ['ADM', 'CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'buyer-nominate',
          type: 'webform',
        },
        {
          config: {},
          customerText: "Buyer's Questionnaire",
          depends: [
            {
              id: 'buyer-nominate',
              name: 'Buyer Contact Authority',
            },
          ],
          doctype: 'bq',
          explanation:
            'Please complete this document to provide us with information we need to proceed.',
          external: [],
          internal: false,
          milestone: false,
          name: "Buyer's Questionnaire",
          notifications: [],
          optional: false,
          permissions: {
            download: [],
            edit: ['ADM', 'CON', 'PM', 'CUS'],
            skip: [],
            status: ['AGT', 'BRK', 'CON', 'PM', 'CUS'],
            view: ['ADM', 'CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'buyer-q',
          type: 'webform',
        },
        {
          config: {},
          customerText: 'Upload signed Contract of Sale',
          depends: [
            {
              id: 'assign-con',
              name: 'Assign conveyancer',
            },
          ],
          doctype: 'cos',
          explanation:
            "If you haven't already provided the Contract of Sale, you can upload it here.",
          external: [],
          internal: false,
          logic: 'before if document.cos.signed complete me',
          milestone: false,
          name: 'Upload signed Contract of Sale',
          notifications: [
            {
              method: 'SMS',
              number: 39,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.551',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 551,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.551',
              trigger: 'complete',
            },
          ],
          optional: true,
          permissions: {
            download: ['ADM', 'CON', 'PM', 'CUS'],
            skip: ['ADM', 'CON', 'PM'],
            status: ['AGT', 'ADM', 'BRK'],
            upload: ['ADM', 'CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'upload-signed-cos',
          type: 'upload',
        },
        {
          config: {},
          customerText: 'Engagement Letter',
          depends: [
            {
              id: 'upload-signed-cos',
              name: 'Upload signed Contract of Sale',
            },
            {
              id: 'buyer-nominate',
              name: 'Buyer Contact Authority',
            },
          ],
          doctype: 'egl',
          explanation:
            'Your conveyancer will send you this letter to explain the conveyancing process.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Engagement Letter',
          notifications: [
            {
              method: 'APP',
              number: 552,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.552',
              trigger: 'ready',
            },
            {
              method: 'SMS',
              number: 552,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.552',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            download: ['ADM', 'CON', 'PM'],
            skip: ['ADM'],
            status: ['AGT', 'ADM', 'BRK'],
            upload: ['ADM', 'CON', 'PM'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'engagement-letter',
          type: 'upload',
        },
        {
          config: {},
          customerText: 'Costs Disclosure',
          depends: [
            {
              id: 'upload-signed-cos',
              name: 'Upload signed Contract of Sale',
            },
            {
              id: 'buyer-nominate',
              name: 'Buyer Contact Authority',
            },
          ],
          doctype: 'cdc',
          explanation:
            'You will receive our Costs Disclosure outlining our costs and estimated disbursements.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Complete Costs Disclosure',
          notifications: [],
          optional: false,
          permissions: {
            download: ['ADM', 'CON', 'PM', 'CUS'],
            edit: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS'],
            view: ['ADM', 'CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'cost-disclosure',
          type: 'webform',
        },
        {
          config: {},
          customerText: 'Prepare Engagement documents',
          depends: [
            {
              id: 'buyer-nominate',
              name: 'Buyer Contact Authority',
            },
          ],
          doctype: 'caf',
          explanation:
            'Your conveyancer will prepare an Engagement Letter, Costs Disclosure and Client Authorisation Form.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Prepare Client Authorisation Form',
          notifications: [],
          optional: false,
          permissions: {
            download: [],
            edit: ['ADM', 'CON', 'PM'],
            skip: [],
            status: ['AGT', 'BRK', 'CUS'],
            view: ['ADM', 'CON', 'PM'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'client-auth',
          type: 'webform',
        },
        {
          config: {},
          customerText: 'Approve Engagement Letter',
          depends: [
            {
              id: 'engagement-letter',
              name: 'Upload Engagement Letter',
            },
            {
              id: 'cost-disclosure',
              name: 'Complete Costs Disclosure',
            },
            {
              id: 'client-auth',
              name: 'Prepare Client Authorisation Form',
            },
          ],
          doctype: 'egl',
          explanation:
            'The Settle Easy practice manager checks and approves all important documents to ensure quality of service.',
          external: [],
          internal: false,
          logic: 'after if rejected goto engagement-letter',
          milestone: false,
          name: 'Approve Engagement Letter',
          notifications: [
            {
              method: 'APP',
              number: 554,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.554',
              trigger: 'reject',
            },
            {
              method: 'SMS',
              number: 554,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.554',
              trigger: 'reject',
            },
            {
              method: 'APP',
              number: 650,
              recipients: ['PM'],
              revision: 1,
              text: 'b.app.v.650',
              trigger: 'ready',
            },
            {
              method: 'SMS',
              number: 650,
              recipients: ['PM'],
              revision: 1,
              text: 'b.sms.v.650',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            approve: ['PM'],
            download: ['ADM', 'CON', 'PM', 'CUS'],
            reject: ['ADM', 'PM'],
            skip: ['ADM'],
            status: ['AGT', 'BRK', 'CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Practice manager',
          role: 'PM',
          slug: 'approve-egl',
          type: 'approve',
        },
        {
          config: {
            type: 'approve',
          },
          customerText: 'Costs Disclosure',
          depends: [
            {
              id: 'cost-disclosure',
              name: 'Complete costs disclosure',
            },
          ],
          doctype: 'cdc',
          explanation:
            'The Settle Easy practice manager checks and approves all important documents to ensure quality of service.',
          external: [],
          internal: false,
          logic: 'after if rejected goto cost-disclosure',
          milestone: false,
          name: 'Approve Costs Disclosure',
          notifications: [],
          optional: false,
          permissions: {
            approve: ['ADM', 'PM'],
            download: ['ADM', 'PM', 'CUS'],
            reject: [],
            skip: ['ADM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Practice manager',
          role: 'PM',
          slug: 'approve-cdc',
          type: 'approve',
        },
        {
          config: {
            signOnly: true,
            type: 'approve',
          },
          customerText: 'Review Client Authorisation Form',
          depends: [
            {
              id: 'client-auth',
              name: 'Prepare Client Authorisation Form',
            },
          ],
          doctype: 'caf',
          explanation:
            'The Settle Easy practice manager checks and approves all important documents to ensure quality of service.',
          external: [],
          internal: false,
          logic: 'after if rejected goto client-auth',
          milestone: false,
          name: 'Review Client Authorisation Form',
          notifications: [
            {
              method: 'APP',
              number: 651,
              recipients: ['PM'],
              revision: 1,
              text: 'b.app.v.651',
              trigger: 'ready',
            },
            {
              method: 'SMS',
              number: 651,
              recipients: ['PM'],
              revision: 1,
              text: 'b.sms.v.651',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            download: ['ADM', 'CON', 'PM'],
            edit: ['ADM', 'PM'],
            skip: [],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'DIR', 'OA', 'CUS'],
            view: ['ADM', 'PM'],
          },
          priority: 5,
          responsible: 'Practice manager',
          role: 'PM',
          slug: 'approve-caf',
          type: 'webform',
        },
        {
          config: {},
          customerText: 'Read Engagement Letter',
          depends: [
            {
              id: 'approve-egl',
              name: 'Approve Engagement Letter',
            },
          ],
          doctype: 'egl',
          explanation:
            'The Engagement Letter will highlight some important information about the conveyancing process.',
          external: [],
          instructions:
            'The Engagement Letter will highlight some important information about the conveyancing process.\nIt is important for you to read the letter and once you have read it, click the complete button.',
          internal: false,
          milestone: false,
          name: 'Read Engagement Letter',
          notifications: [],
          optional: false,
          permissions: {
            approve: ['ADM', 'CUS'],
            download: ['ADM', 'CUS'],
            reject: ['ADM', 'CUS'],
            skip: ['ADM'],
            status: ['ADM', 'CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'read-egl',
          type: 'approve',
        },
        {
          config: {
            signOnly: true,
          },
          customerText: 'Sign Costs Disclosure',
          depends: [
            {
              id: 'approve-cdc',
              name: 'Approve Costs Disclosure',
            },
          ],
          doctype: 'cdc',
          explanation:
            'The Costs Agreement and Disclosure sets out our costs and estimated disbursements, together with important terms relating to our engagement.',
          external: [],
          instructions: 'Please click the button to sign the Costs Disclosure.',
          internal: false,
          milestone: false,
          name: 'Sign Costs Disclosure',
          notifications: [],
          optional: false,
          permissions: {
            download: ['ADM'],
            edit: ['ADM'],
            skip: ['ADM'],
            status: ['ADM', 'CON', 'PM', 'CUS'],
            view: ['ADM', 'CUS'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'sign-cdc',
          type: 'webform',
        },
        {
          config: {
            signOnly: true,
          },
          customerText: 'Client Authorisation Form',
          depends: [
            {
              id: 'approve-caf',
              name: 'Review Client Authorisation Form',
            },
            {
              id: 'approve-egl',
              name: 'Approve Engagement Letter',
            },
            {
              id: 'approve-cdc',
              name: 'Approve Costs Disclosure',
            },
          ],
          doctype: 'caf',
          explanation:
            'This form authorises us to act as your conveyancer and attend to the settlement.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Customer signs CAF',
          notifications: [
            {
              method: 'SMS',
              number: 221,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.221',
              trigger: 'ready',
            },
            {
              method: 'EMAIL',
              number: 221,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.e.v.221',
              trigger: 'ready',
            },
            {
              method: 'APP',
              number: 221,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.221',
              trigger: 'ready',
            },
            {
              method: 'SMS',
              number: 553,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.553',
              trigger: 'ready',
            },
            {
              method: 'APP',
              number: 553,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.553',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            download: ['ADM', 'CON', 'PM'],
            edit: ['ADM', 'CUS'],
            skip: ['ADM'],
            status: ['ADM', 'CON', 'PM'],
            view: ['ADM', 'CUS'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'sign-caf',
          type: 'webform',
        },
      ],
    },
    {
      name: 'Contract',
      slug: 'contract',
      steps: [
        {
          config: {},
          customerText: 'Initial documents review',
          depends: [
            {
              id: 'sign-caf',
              name: 'Customer signs CAF',
            },
            {
              id: 'read-egl',
              name: 'Read Engagement Letter',
            },
            {
              id: 'sign-cdc',
              name: 'Sign Costs Disclosure',
            },
            {
              id: 'buyer-q',
              name: "Buyer's Questionnaire",
            },
          ],
          description:
            'The conveyancer will cross check information gathered so far, and make sure everything is consistent and complete.',
          doctype: 'na',
          explanation:
            'Your conveyancer will review the initial documents to check we have everything we need to proceed.',
          external: [
            {
              done: false,
              id: 'contact-auth',
              name: 'Contact Authority',
              optional: false,
            },
            {
              done: false,
              id: 'bq',
              name: "Buyer's Questionnaire",
              optional: false,
            },
            {
              done: false,
              id: 'client-auth',
              name: 'Client Authorisation',
              optional: false,
            },
            {
              done: false,
              id: 'cdc',
              name: 'Costs Disclosure',
              optional: false,
            },
          ],
          instructions:
            'I confirm that I have reviewed and am satisfied with the following documents:',
          internal: false,
          milestone: false,
          name: 'Review initial documents',
          notifications: [
            {
              method: 'SMS',
              number: 556,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.556',
              trigger: 'ready',
            },
            {
              method: 'APP',
              number: 556,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.556',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            complete: ['ADM', 'CON', 'PM', 'CUS'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'go-ahead',
          type: 'external',
        },
        {
          config: {},
          customerText: 'VOI Launcher',
          depends: [
            {
              id: 'sign-caf',
              name: 'Customer signs CAF',
            },
          ],
          doctype: 'voi',
          explanation:
            'This is a system step, to initiate the request for VOI with the remote system.',
          external: [],
          internal: true,
          milestone: false,
          name: 'VOI launcher',
          notifications: [],
          optional: false,
          permissions: {
            complete: ['ADM', 'PM', 'SYS'],
            skip: ['ADM', 'PM', 'SYS'],
            status: ['ADM', 'CON', 'PM', 'SYS'],
          },
          priority: 5,
          responsible: 'System',
          role: 'SYS',
          slug: 'launch-voi',
          type: 'bot',
        },
        {
          config: {},
          customerText: 'Verify buyer identity',
          depends: [
            {
              id: 'launch-voi',
              name: 'VOI Launcher',
            },
          ],
          description:
            'Condition: \n  * If buyer(s) have current VOI credentials on file, complete the task, and attach VOI doc to job\n  * Call API to see if buyer(s) have current VOI credentials, if so, complete the task, and attach VOI doc to job\n\nFor each buyer that needs a VOI check, \n  * Create a workflow task for buyer VOI\n  * Call API to add VOI request\n  * Send "ready" email to buyer\n\nAs each customer completes the VOI, a webhook will fire an API on our server.\n\nWe check the status, and then do the following: \n  * Upload the results document to S3\n  * Marking it as a VOI document on the user\'s profile \n  * Complete this task',
          doctype: 'voi',
          explanation:
            'All parties to a property transaction must have their identities verified. To complete this step, please have your original identity documents handy.',
          external: [
            {
              done: false,
              id: '999',
              name: 'Checkbox label goes here',
              optional: false,
            },
          ],
          internal: false,
          milestone: false,
          name: 'Verify buyer identity',
          notifications: [
            {
              method: 'SMS',
              number: 222,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.222',
              trigger: 'ready',
            },
            {
              method: 'APP',
              number: 222,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.222',
              trigger: 'ready',
            },
            {
              method: 'EMAIL',
              number: 222,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.e.v.222',
              trigger: 'ready',
            },
            {
              method: 'SMS',
              number: 557,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.557',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 557,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.557',
              trigger: 'complete',
            },
          ],
          optional: false,
          permissions: {
            download: ['ADM', 'CON', 'PM', 'CUS'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
            upload: ['ADM', 'CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'voi',
          type: 'voi',
        },
        {
          config: {},
          customerText: "All VOI's completed",
          depends: [
            {
              id: 'voi',
              name: 'Verify buyer identity',
            },
          ],
          doctype: 'voi',
          explanation: "This is a system step, which collates all individual VOI's",
          external: [],
          internal: true,
          milestone: false,
          name: "All VOI's completed",
          notifications: [
            {
              method: 'SMS',
              number: 557,
              recipients: ['CON'],
              revision: 1,
              text: 'sms-255-voi-all',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 557,
              recipients: ['CON'],
              revision: 1,
              text: 'app-255-voi-all',
              trigger: 'complete',
            },
          ],
          optional: false,
          permissions: {
            approve: ['PM'],
            complete: ['CON', 'CUS'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'System',
          role: 'SYS',
          slug: 'voi-all',
          type: 'bot',
        },
        {
          config: {},
          customerText: 'Property searches and enquiries',
          depends: [
            {
              id: 'go-ahead',
              name: 'Go ahead',
            },
          ],
          doctype: 'na',
          explanation: 'Your conveyancer will begin property searches and enquiries.',
          external: [
            {
              done: false,
              id: 'title-search',
              name: 'Title search and enquiries completed',
              optional: false,
            },
          ],
          internal: false,
          milestone: false,
          name: 'Property search and enquiries',
          notifications: [],
          optional: false,
          permissions: {
            approve: [],
            complete: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'title-search',
          type: 'external',
        },
        {
          config: {},
          customerText: 'Confirm that purchase is unconditional',
          depends: [
            {
              id: 'go-ahead',
              name: 'Review initial documents',
            },
          ],
          description:
            'Ensure that all contract conditions have been, no adverse searches have been received and all parties are ready to proceed to settlement.',
          doctype: 'na',
          explanation:
            'Once all conditions in the contract are met (if any), your purchase becomes unconditional and we’ll begin preparing for settlement.',
          external: [
            {
              done: false,
              id: 'all-conditions',
              name: 'All conditions have been satisfied',
              optional: false,
            },
            {
              done: false,
              id: 'adverse-search',
              name: 'No adverse search results have been received',
              optional: false,
            },
            {
              done: false,
              id: 'settle-proceed',
              name: 'All parties are ready to proceed to settlement',
              optional: false,
            },
          ],
          instructions:
            'I have reviewed the contract, finance approval, searches and other documents and confirm:',
          internal: false,
          milestone: false,
          name: 'Purchase is unconditional',
          notifications: [
            {
              method: 'EMAIL',
              number: 223,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.e.v.223',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 223,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.223',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 223,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.223',
              trigger: 'complete',
            },
            {
              method: 'EMAIL',
              number: 223,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.e.v.223',
              trigger: 'skip',
            },
          ],
          optional: false,
          permissions: {
            complete: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'CON', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'unconditional',
          type: 'external',
        },
        {
          config: {},
          customerText: 'Deposit release request',
          depends: [
            {
              id: 'unconditional',
              name: 'Purchase is unconditional',
            },
          ],
          doctype: 's27',
          explanation:
            'Conveyancer prepares the request for a release of the deposit to the seller.',
          external: [
            {
              done: false,
              id: 'title-search',
              name: 'Title search and enquiries completed',
              optional: false,
            },
          ],
          internal: false,
          logic: 'after if skipped skip sign-s27-1',
          milestone: false,
          name: 'Section 27 request',
          notifications: [
            {
              method: 'SMS',
              number: 27,
              recipients: ['CUS'],
              revision: 1,
              text: 'sms-sign-s27',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 27,
              recipients: ['CUS'],
              revision: 1,
              text: 'app-sign-s27',
              trigger: 'complete',
            },
          ],
          optional: true,
          permissions: {
            prep: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'CON', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'process-s27-1',
          type: 'prepv2',
        },
        {
          config: {},
          customerText: 'Early release of deposit',
          depends: [
            {
              id: 'process-s27-1',
              name: 'Process section 27',
            },
          ],
          doctype: 's27',
          explanation:
            'The seller may request an early release of the deposit monies. Your conveyancer will advise if this happens.',
          external: [
            {
              done: false,
              id: 'unconditional-sale',
              name: 'Sale is unconditional',
              optional: false,
            },
          ],
          instructions:
            'If you have spoken to your conveyancer and have agreed to release the deposit monies, please sign and submit this document.',
          internal: false,
          milestone: false,
          name: 'Review and sign Section 27',
          notifications: [
            {
              method: 'SMS',
              number: 1,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.563',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 1,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.563',
              trigger: 'complete',
            },
          ],
          optional: true,
          permissions: {
            sign: ['CUS'],
            skip: ['ADM', 'CON', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Customer',
          role: 'CUS',
          slug: 'sign-s27-1',
          type: 'signv2',
        },
      ],
    },
    {
      name: 'Settlement',
      slug: 'settle',
      steps: [
        {
          config: {},
          customerText: 'Settlement date and time',
          depends: [
            {
              id: 'unconditional',
              name: 'Sale is unconditional',
            },
          ],
          doctype: 'na',
          explanation:
            'We will notify you as soon as the settlement date and time have been scheduled.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Set settlement date and time',
          notifications: [
            {
              method: 'SMS',
              number: 224,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.224',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 224,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.224',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 421,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.sms.v.421',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 421,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.app.v.421',
              trigger: 'complete',
            },
          ],
          optional: false,
          permissions: {
            complete: ['ADM', 'CON', 'PM', 'CUS'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'settle-date-time',
          type: 'set-date-time',
        },
        {
          config: {},
          customerText: 'Send buyer alert: SRO email',
          depends: [
            {
              id: 'settle-date-time',
              name: 'Set settlement date and time',
            },
          ],
          doctype: 'na',
          explanation:
            'Send notification to buyer to expect an email from the State Revenue Office (SRO), and to respond to it promptly.',
          external: [],
          internal: true,
          milestone: false,
          name: 'Send buyer alert: SRO email',
          notifications: [
            {
              method: 'SMS',
              number: 226,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.226',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 226,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.226',
              trigger: 'complete',
            },
          ],
          optional: false,
          permissions: {
            send: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'buyer-sro',
          type: 'notification',
        },
        {
          config: {},
          customerText: 'Final inspection reminder',
          depends: [
            {
              id: 'settle-date-time',
              name: 'Set settlement date and time',
            },
          ],
          doctype: 'na',
          explanation:
            'This is a notification step, to remind the buyer about doing a final inspection of the property prior to settlement.',
          external: [],
          internal: true,
          milestone: false,
          name: 'Final inspection reminder',
          notifications: [
            {
              method: 'SMS',
              number: 227,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.227',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 227,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.227',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 422,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.sms.v.422',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 422,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.app.v.422',
              trigger: 'complete',
            },
          ],
          optional: false,
          permissions: {
            send: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'final-inspection',
          type: 'notification',
        },
        {
          config: {},
          customerText: 'Statement of Adjustments and Statement of Costs',
          depends: [
            {
              id: 'settle-date-time',
              name: 'Set settlement date and time',
            },
          ],
          doctype: 'soass',
          explanation:
            'These two documents contain important financial information for your approval before settlement.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Upload Statement of Adjustments',
          notifications: [
            {
              method: 'SMS',
              number: 558,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.558',
              trigger: 'ready',
            },
            {
              method: 'APP',
              number: 558,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.558',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            download: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM'],
            upload: ['ADM', 'CON', 'PM'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'upload-soa',
          type: 'upload',
        },
        {
          config: {},
          customerText: 'Statement of Costs',
          depends: [
            {
              id: 'settle-date-time',
              name: 'Set settlement date and time',
            },
          ],
          doctype: 'stc',
          explanation:
            "The statement of costs is a document detailing the costs that Settle Easy have incurred on the buyer's behalf.",
          external: [],
          internal: false,
          milestone: false,
          name: 'Upload Statement of Costs',
          notifications: [],
          optional: false,
          permissions: {
            download: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM'],
            upload: ['ADM', 'CON', 'PM'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'upload-soc',
          type: 'upload',
        },
        {
          config: {},
          customerText: 'Upload Settle Easy tax invoice',
          depends: [
            {
              id: 'settle-date-time',
              name: 'Set settlement date and time',
            },
          ],
          doctype: 'tiv',
          explanation:
            'Settle Easy must provide an invoice to be included in settlement statement.',
          external: [],
          internal: false,
          milestone: false,
          name: 'Upload Settle Easy Tax Invoice',
          notifications: [],
          optional: false,
          permissions: {
            download: [],
            skip: [],
            status: ['AGT', 'BRK'],
            upload: ['CON', 'PM'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'upload-invoice',
          type: 'upload',
        },
        {
          config: {},
          customerText: 'Approve SOA and settlement statement',
          depends: [
            {
              id: 'upload-soa',
              name: 'Upload Statement of Adjustments',
            },
            {
              id: 'upload-soc',
              name: 'Upload Statement of Costs',
            },
          ],
          doctype: 'soass',
          explanation:
            'Approve the statement of adjustments and the settlement statement.',
          external: [],
          internal: false,
          logic: 'after if rejected goto upload-soa\nafter if rejected goto upload-soc',
          milestone: false,
          name: 'Approve SOA',
          notifications: [
            {
              method: 'SMS',
              number: 652,
              recipients: ['PM'],
              revision: 1,
              text: 'b.sms.v.652',
              trigger: 'ready',
            },
            {
              method: 'APP',
              number: 652,
              recipients: ['PM'],
              revision: 1,
              text: 'b.app.v.652',
              trigger: 'ready',
            },
            {
              method: 'SMS',
              number: 560,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.560',
              trigger: 'reject',
            },
            {
              method: 'APP',
              number: 560,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.560',
              trigger: 'reject',
            },
            {
              method: 'EMAIL',
              number: 225,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.e.v.225',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 225,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.225',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 225,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.225',
              trigger: 'complete',
            },
          ],
          optional: false,
          permissions: {
            approve: ['ADM', 'PM'],
            download: ['ADM'],
            reject: ['ADM', 'PM'],
            skip: ['ADM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Practice manager',
          role: 'PM',
          slug: 'approve-soa',
          type: 'approve',
        },
        {
          config: {},
          customerText: 'Approve SOC',
          depends: [
            {
              id: 'upload-soc',
              name: 'Upload statement of costs',
            },
          ],
          doctype: 'stc',
          explanation: 'Approve the statement of costs.',
          external: [],
          internal: false,
          logic: 'after if rejected goto upload-soa\nafter if rejected goto upload-soc',
          milestone: false,
          name: 'Approve SOC',
          notifications: [
            {
              method: 'SMS',
              number: 560,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.560',
              trigger: 'reject',
            },
            {
              method: 'APP',
              number: 560,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.560',
              trigger: 'reject',
            },
          ],
          optional: false,
          permissions: {
            approve: ['ADM', 'PM'],
            download: ['ADM', 'CON', 'PM'],
            reject: ['ADM', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['CON', 'PM', 'CUS'],
          },
          priority: 5,
          responsible: 'Practice manager',
          role: 'PM',
          slug: 'approve-soc',
          type: 'approve',
        },
        {
          config: {},
          customerText: 'Settlement completion',
          depends: [
            {
              id: 'final-inspection',
              name: 'Final inspection reminder',
            },
            {
              id: 'upload-invoice',
              name: 'Upload Settle Easy tax invoice',
            },
            {
              id: 'approve-soa',
              name: 'Approve SOA and settlement statement',
            },
            {
              id: 'approve-soc',
              name: 'Approve SOC',
            },
            {
              id: 'voi-all',
              name: "All VOI's completed",
            },
            {
              id: 'title-search',
              name: 'Property search and enquiries',
            },
          ],
          doctype: 'na',
          explanation: 'Your conveyancer will let you know once settlement is complete.',
          external: [
            {
              done: false,
              id: 'pexa-confirm',
              name: 'Tick box once complete',
              optional: false,
            },
          ],
          instructions:
            'Confirm PEXA settlement and download and save all PEXA settlement records to the customer file.',
          internal: false,
          logic: 'after if listing.status.active settle me',
          milestone: false,
          name: 'Settlement completion',
          notifications: [
            {
              method: 'SMS',
              number: 423,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.sms.v.423',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 423,
              recipients: ['AGT'],
              revision: 1,
              text: 'b.app.v.423',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 561,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.561',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 561,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.561',
              trigger: 'complete',
            },
            {
              method: 'EMAIL',
              number: 720,
              recipients: ['PM'],
              revision: 1,
              text: 'b.e.v.653',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 720,
              recipients: ['PM'],
              revision: 1,
              text: 'b.app.v.653',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 228,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.sms.v.228',
              trigger: 'complete',
            },
            {
              method: 'APP',
              number: 228,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.app.v.228',
              trigger: 'complete',
            },
            {
              method: 'EMAIL',
              number: 228,
              recipients: ['CUS'],
              revision: 1,
              text: 'b.e.v.228',
              trigger: 'complete',
            },
            {
              method: 'SMS',
              number: 559,
              recipients: ['CON'],
              revision: 1,
              text: 'b.sms.v.559',
              trigger: 'ready',
            },
            {
              method: 'APP',
              number: 559,
              recipients: ['CON'],
              revision: 1,
              text: 'b.app.v.559',
              trigger: 'ready',
            },
          ],
          optional: false,
          permissions: {
            complete: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'confirm-pexa',
          type: 'external',
        },
        {
          config: {},
          customerText: 'Notices to authorities',
          depends: [
            {
              id: 'confirm-pexa',
              name: 'Settlement confirmation',
            },
          ],
          doctype: 'na',
          explanation:
            'After settlement, your conveyancer will notify council and water authorities that you now own the property.',
          external: [
            {
              done: false,
              id: 'send-notices-auth',
              name: 'Send notices to authorities',
              optional: false,
            },
          ],
          internal: true,
          milestone: false,
          name: 'Send notices to authorities',
          notifications: [],
          optional: false,
          permissions: {
            complete: ['ADM', 'CON', 'PM'],
            skip: ['ADM', 'PM'],
            status: ['AGT', 'ADM', 'BRK', 'CON', 'PM', 'CUS', 'RAD'],
          },
          priority: 5,
          responsible: 'Conveyancer',
          role: 'CON',
          slug: 'notify-authorities',
          type: 'external',
        },
      ],
    },
  ],
  version: 158,
}
