/* Generated file DO NOT EDIT !!!
 * Generated by /Users/mikkel/easy/settler/scripts/generate-admin-files.js at 18-07-2021 20:07:10
*/
//
// This file contains a list of publications for database admin pages
// It is generated from a list of modules
//
// Note that no code is necessary here, each api declares its own publications.
// This file is to bring them together, and in the darkness bind them.
//
// GENERATED PUBS GO HERE

import '/imports/api/audits/server/publications'
import '/imports/api/cronjobs/server/publications'
import '/imports/api/triggers/server/publications'
import '/imports/api/message-templates/server/publications'
import '/imports/api/messages/server/publications'
import '/imports/api/notifications/server/publications'
import '/imports/api/members/server/publications'
import '/imports/api/settings/server/publications'
import '/imports/api/surveys/server/publications'
import '/imports/api/events/server/publications'
import '/imports/api/courses/server/publications'
import '/imports/api/tools/server/publications'
import '/imports/api/sessions/server/publications'
import '/imports/api/service-items/server/publications'
import '/imports/api/jobs/server/publications'
import '/imports/api/forms/server/publications'
import '/imports/api/registrations/server/publications'
import '/imports/api/collections/server/publications'
import '/imports/api/standups/server/publications'
import '/imports/api/teams/server/publications'
import '/imports/api/pdf-templates/server/publications'

// END GENERATED PUBS
