/* Generated file DO NOT EDIT !!!
 * Generated by /Users/mikkel/easy/settler/scripts/generate-admin-files.js at 18-07-2021 20:07:10
*/
//
// This file contains a list of publications for database admin pages
// It is generated from a list of modules
//
// Note that no code is necessary here, each api declares its own publications.
// This file is to bring them together, and in the darkness bind them.
//
// GENERATED PUBS GO HERE

<%= publications %>

// END GENERATED PUBS
