version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mounts/data/db:/data/db
  web:
    # image: b2bikes-api-img
    build:
      context: .
      args:
        - NODE_ENV:development
    depends_on:
      - db
    ports:
      - 5858:5858
      - 9229:9229
      - 3000:3000
    command: ["./wait-for-it.sh", "db:27017", "--strict", "--", "npm", "start"]
    environment:
      NODE_ENV: development
      MONGO_URI: "mongodb://db:27017/b2bikes-db"