/**
 * WARNING: This file is generated by scripts/bind-collections.js
 * - The script looks in /imports/api for folders ending in 's' and
 * the code below is generated from that list.
 * Some folders are explicitly excluded, such as 'users', 'audits', 'logs' etc
 *
 * DO NOT EDIT!!!
 */
import Assessments, { AssessmentsSchema } from '/imports/api/assessments/schema'
import Courses, { CoursesSchema } from '/imports/api/courses/schema'
import Cronjobs, { CronjobsSchema } from '/imports/api/cronjobs/schema'
import Events, { EventsSchema } from '/imports/api/events/schema'
import Forms, { FormsSchema } from '/imports/api/forms/schema'
import Jobs, { JobsSchema } from '/imports/api/jobs/schema'
import Members, { MembersSchema } from '/imports/api/members/schema'
import MessageTemplates, {
  MessageTemplatesSchema,
} from '/imports/api/message-templates/schema'
import Messages, { MessagesSchema } from '/imports/api/messages/schema'
import Notifications, { NotificationsSchema } from '/imports/api/notifications/schema'
import Registrations, { RegistrationsSchema } from '/imports/api/registrations/schema'
import ServiceItems, { ServiceItemsSchema } from '/imports/api/service-items/schema'
import Sessions, { SessionsSchema } from '/imports/api/sessions/schema'
import Settings, { SettingsSchema } from '/imports/api/settings/schema'
import StandupNotes, { StandupNotesSchema } from '/imports/api/standup-notes/schema'
import Surveys, { SurveysSchema } from '/imports/api/surveys/schema'
import Tools, { ToolsSchema } from '/imports/api/tools/schema'
import Triggers, { TriggersSchema } from '/imports/api/triggers/schema'

const getCollection = (name) => {
  switch (name) {
    case 'assessments':
      return { collection: Assessments, schema: AssessmentsSchema }
    case 'courses':
      return { collection: Courses, schema: CoursesSchema }
    case 'cronjobs':
      return { collection: Cronjobs, schema: CronjobsSchema }
    case 'events':
      return { collection: Events, schema: EventsSchema }
    case 'forms':
      return { collection: Forms, schema: FormsSchema }
    case 'jobs':
      return { collection: Jobs, schema: JobsSchema }
    case 'members':
      return { collection: Members, schema: MembersSchema }
    case 'message-templates':
      return { collection: MessageTemplates, schema: MessageTemplatesSchema }
    case 'messages':
      return { collection: Messages, schema: MessagesSchema }
    case 'notifications':
      return { collection: Notifications, schema: NotificationsSchema }
    case 'registrations':
      return { collection: Registrations, schema: RegistrationsSchema }
    case 'service-items':
      return { collection: ServiceItems, schema: ServiceItemsSchema }
    case 'sessions':
      return { collection: Sessions, schema: SessionsSchema }
    case 'settings':
      return { collection: Settings, schema: SettingsSchema }
    case 'standup-notes':
      return { collection: StandupNotes, schema: StandupNotesSchema }
    case 'surveys':
      return { collection: Surveys, schema: SurveysSchema }
    case 'tools':
      return { collection: Tools, schema: ToolsSchema }
    case 'triggers':
      return { collection: Triggers, schema: TriggersSchema }
    default:
      return null
  }
}

export default getCollection
