import React, { Suspense, lazy } from 'react'
import { Route, Switch } from 'react-router-dom'

/**  Generated file DO NOT EDIT !!!
 * Generated by /Users/mikkel/easy/settler/scripts/generate-admin-files.js at 18-07-2021 20:07:10
*/
import Loading from '/imports/ui/components/commons/loading.js'

// Generated lazy imports go here...

<%= routeImports %>

//
// This file contains a list of routes for database admin pages
// It is generated from a list of modules
//
export default GeneratedRoute = () => {
  return (
    <Suspense fallback={<Loading loading />}>
      <Switch>
        {/** Generated routes go here */}
        <%= routeMarkup %>
      </Switch>
    </Suspense>
  )
}
