import React from 'react'
import { Route } from 'react-router-dom'
/* Generated file DO NOT EDIT !!!
 * Generated by /Users/mikkel/easy/settler/scripts/generate-admin-files.js at 18-07-2021 20:07:10
*/// Import all of the DB UI components
<%= routeImports %>

//
// This file contains a list of routes for database admin pages
// It is generated from a list of modules
//
export default GeneratedRoute = () => (
  <>
    <%= routeMarkup %>
  </>
)
