[
  {
    "date": "17 May 2017",
    "email": "Dis0001@camhigh.vic.edu.au",
    "firstname": "Nimai",
    "lastname": "Disley",
    "address": "12 Barbara Ave Glen Iris",
    "suburb": "Glen Iris",
    "state": "Victoria",
    "postcode": "3146",
    "phone": "4060 647118",
    "mobile": "4060 647118",
    "emergencyContact": "Jasmine Main",
    "emergencyEmail": "Jasmine.m.main@gmail.com",
    "emergencyPhone": "0449 286676",
    "emergencyMobile": "0449 286676",
    "workStatus": "Student",
    "bikes": "4",
    "primaryBike": "Fixie/Single speed",
    "reasons": "My Name is Nimai\nI am currently completing Year 10 at Camberwell High School (CHS).\nAs part of the 2017 Careers and Pathways Program I have to complete one week of Work Experience.\nI am a dedicated bike rider and I have an eager interest in the construction and maintenance of bikes.\nI am really keen to learn about any aspect of the design, construction, repair and production of bicycles.\nThis would support my Year 10 objectives and provide me a valuable real-world insight into a local industry success and discover more about my options beyond school.\nI am a capable and independent learner with a great aptitude, resilience and sense of team.\nThe dates set by CHS are the 26 - 30th of June 2017.\nI have completed a Work Safe “General Module” and understand general professional workplace demands.\nIt would be awesome to have an opportunity to spend a week with your company and team for my Work Experience.\nI am really hopeful and looking forward to hearing back from you soon."
  },
  {
    "date": "22 May 2017",
    "email": "ckwcolby@gmail.com",
    "firstname": "KeatWah",
    "lastname": "CHEW",
    "address": "13 Cottrell Street",
    "suburb": "Werribee",
    "state": "VIC",
    "postcode": "3030",
    "phone": "0414 885238",
    "mobile": "0414 885238",
    "emergencyContact": "PeiWah CHEW",
    "emergencyEmail": "peiwah_chew@yahoo.com",
    "emergencyPhone": "0433 543904",
    "emergencyMobile": "0433 543904",
    "workStatus": "Part time work",
    "bikes": "0",
    "primaryBike": "Select -->",
    "reasons": "I used to have a bike but got stolen.\n\nI'm interested in bike maintenance and love to have the hands-on experience in this area."
  },
  {
    "date": "23 May 2017",
    "email": "stefan_gabriel@icloud.com",
    "firstname": "Stefan",
    "lastname": "Gabriel",
    "address": "23 Leveson Street",
    "suburb": "North Melbourne",
    "postcode": "3051",
    "phone": "+61 434165979",
    "emergencyContact": "Melitta Beck",
    "emergencyEmail": "bemelitta@googlemail.com",
    "emergencyPhone": "+61 413896144",
    "workStatus": "Unemployed",
    "bikes": "1",
    "primaryBike": "Fixie/Single speed",
    "reasons": "Bikes make life better - but it s so expensive to get your bike repaired in a store, And if you want to do it yourself you have to buy tools... cycling should be available for everyone! I want to do vulenteer until i find a job as a mechanic ... my background is industrial engineer. My problem is not to find a job - i want to do the job which is good with my mission and view of the world i want to live in..."
  },
  {
    "date": "03 Jun 2017",
    "email": "zbee1@student.monash.edu",
    "firstname": "Zac",
    "lastname": "Beerens",
    "address": "5 Prentice St",
    "suburb": "Elsternwick",
    "state": "VIC",
    "postcode": "3185",
    "phone": "0430 572820",
    "mobile": "0430 572820",
    "emergencyContact": "Kirsten Beerens",
    "emergencyEmail": "kirstenfbeerens@hotmail.com",
    "emergencyPhone": "O409704209",
    "emergencyMobile": "0409 704209",
    "workStatus": "Student",
    "bikes": "2",
    "primaryBike": "Road/racer",
    "reasons": "I started learning basic bicycle maintenance over the last 4 months after my girlfriend started to get involved with the sport, and I guess I got dragged into it with her. Since then I ride 5-6 days a week and have retired my car in favour of 2 wheels. In the last 4 months I have spent at least 100 hours at The Bikery (a non-profit bike shop based at Monash University) building up bikes, helping people fix their bikes and learning as much as I possibly can. To say I'm obsessed would probably be an understatement. I love riding, building and helping others both find the sport and to get back on the road - Volunteering scratches all of those itches. One day I hope to become a paid mechanic, but for now I'm just happy being up to my elbows in bike parts and grease while hopefully passing on my love for hitting the road. I have a lot of time to spare during the week so I'm hoping to use this time to learn as much as possible."
  }
];
